[tool.poetry]
name = "blockingpy"
version = "0.1.0"
description = "Python port of R's blocking package  for blocking records for record linkage and data deduplication based on ANN algorithms."
authors = ["Tymoteusz Strojny <tymek.strojny@gmail.com>"]
readme = "README.md"
packages = [{include = "blockingpy"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.21"
annoy = "^1.17.3"
hnswlib = "^0.8.0"
scipy = ">=1.5.0"
pynndescent = "^0.5.13"
scikit-learn = "^1.5.2"
networkx = "^3.1"
nltk = "^3.9.1"
voyager = "^2.0.9"
faiss-cpu = "^1.9.0"
mlpack = ">=4.4.0,<5.0.0"
pandas = ">=2.2.0,<3.0.0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
mypy = "^1.13.0"
flake8 = "^7.1.1"
pytest = "^8.3.3"
pytest-cov = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
